### ISSUE TITLE
Example of this working

### ISSUE THREAD

**Issue by guysoft** [SketchyFletchy/Hexy-Rugger#1]
Do you have any picture of output of this?
Or something that was made according to instructions it gave out?

**Comment by SketchyFletchy** [comment]
Ha, sorry, I haven’t looked at this repo in a very long time. Here’s a parameter file and the output SVG it generated.

``` json
{
    "width": 10,
    "height": 14,
    "windowWidth": 120,
    "windowHeight": 100,
    "alternateRows": "in",
    "hexHeight": 10,
    "colours": [
        [0.7,1,0.7],
        [0.1,0.9,0.2],
        [0.05,0.6,0.2],
        [0.2,0.35,0.6]
    ],
    "gradientAngle": 90,
    "scatter": 0.6
}
```

![latest](https://user-images.githubusercontent.com/1403652/200411371-c5f595ee-1f1a-40be-8321-62a92bb84598.svg)
